[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn inventory_management.wsgi"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.envs]
PYTHON_VERSION = "3.12"
DJANGO_SETTINGS_MODULE = "inventory_management.settings"
DEBUG = "False" 