[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn inventory_management.wsgi --timeout 60"
healthcheckPath = "/admin/login/"
healthcheckTimeout = 200
restartPolicyType = "on_failure"

[[deploy.healthcheck]]
path = "/admin/login/"
interval = "15s"
timeout = "10s"
retries = 3
grace_period = "20s"

[deploy.envs]
PYTHON_VERSION = "3.12"
DJANGO_SETTINGS_MODULE = "inventory_management.settings"
DEBUG = "False"
ALLOWED_HOSTS = "*.up.railway.app,localhost,127.0.0.1"

[deploy.variables]
DATABASE_URL = "${DATABASE_URL}" 